#!/usr/bin/env python3
"""generate-team v3 — deterministic core.

Detects a project's disciplines (deterministic table), composes the declarative team.yaml
roster (roles = loop steps, resolved by discipline), and marker-merges a human-readable dev
block into AGENTS.md. Stacks the table doesn't cover are reported as GAPS for the wrapping
skill to resolve by judgment and promote back into team_table.py.

Output is timestamp-free, so the same (repo, direction) reproduces the same team.yaml.

usage: gen_team.py [--cwd .] [--direction "one line"] [--out team.yaml] [--agents AGENTS.md] [--quiet]
Prints a summary + any gaps to stdout. Writes team.yaml + the AGENTS.md dev block unless --quiet.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import team_table as T  # noqa: E402

START, END = "<!-- SIMPLE-DEV:TEAM:START -->", "<!-- SIMPLE-DEV:TEAM:END -->"


def _present(root: Path, marker: str) -> bool:
    return bool(list(root.glob(marker[5:]))) if marker.startswith("glob:") else (root / marker).exists()


def detect_disciplines(root: Path) -> list[tuple[str, str, str]]:
    found = []
    for disc, markers, subagent in T.DISCIPLINES:
        for m in markers:
            if _present(root, m):
                found.append((disc, subagent, m.replace("glob:", "")))
                break
    return found


def detect_gaps(root: Path) -> list[dict]:
    return [{"marker": m.replace("glob:", ""), "likely_discipline": d}
            for m, d in T.KNOWN_UNMAPPED.items() if _present(root, m)]


def _flow_list(items: list[str]) -> str:
    return "[" + ", ".join(items) + "]"


def _scalar(v: str) -> str:
    return f'"{v}"' if any(c in v for c in ":#{}[]") else v


def build_team_yaml(project: str, direction: str, disciplines, gaps) -> str:
    L = ["# team.yaml — declarative roster the ScrumMaster reads at dispatch.",
         "# Generated by generate-team v3 (harness/gen_team.py). Regenerate on stack/direction change.",
         "",
         "meta:",
         f"  project: {project}",
         f"  direction_digest: {_scalar(direction)}",
         "",
         "disciplines:"]
    if disciplines:
        for disc, subagent, ev in disciplines:
            L.append(f"  {disc}: {{ subagent_type: {subagent}, via: table, evidence: {_scalar(ev)} }}")
    else:
        L.append("  {}")
    L += ["", "roles:"]
    for role, base in T.ROLES.items():
        L.append(f"  {role}:")
        if role in T.DISCIPLINE_VARYING and disciplines:
            L.append("    by_discipline:")
            for disc, subagent, _ in disciplines:
                L.append(f"      {disc}: {{ subagent_type: {subagent}, skills: {_flow_list(base['skills'])} }}")
            L.append(f"    default: {{ subagent_type: {base['subagent_type']}, skills: {_flow_list(base['skills'])} }}")
        else:
            entry = f"subagent_type: {base['subagent_type']}, skills: {_flow_list(base['skills'])}"
            if base.get("context"):
                entry += f", context: {_flow_list([_scalar(c) for c in base['context']])}"
            L.append(f"    default: {{ {entry} }}")
    L.append("")
    if gaps:
        L.append("gaps:")
        for g in gaps:
            L.append(f"  - {{ marker: {_scalar(g['marker'])}, likely_discipline: {_scalar(g['likely_discipline'])} }}")
    else:
        L.append("gaps: []")
    return "\n".join(L) + "\n"


def agents_block(project: str, disciplines, gaps) -> str:
    L = [f"## Dev team — {project}", "",
         "_Generated by generate-team v3; machine-readable source: `team.yaml`. Do not hand-edit inside the markers._", "",
         "**Disciplines:** " + (", ".join(f"{d} → `{s}`" for d, s, _ in disciplines) or "none detected"), "",
         "**Loop-step roles:**"]
    for role, base in T.ROLES.items():
        skills = ", ".join(f"`{s}`" for s in base["skills"])
        L.append(f"- **{role}** → `{base['subagent_type']}` · {skills}")
    if gaps:
        L += ["", "**Gaps (need judgment, then promote into team_table.py):** "
              + ", ".join(f"`{g['marker']}` ({g['likely_discipline']})" for g in gaps)]
    return "\n".join(L)


def merge_agents(path: Path, block: str) -> str:
    new = f"{START}\n{block}\n{END}"
    if path.exists():
        text = path.read_text()
        if START in text and END in text:
            return text[:text.index(START)] + new + text[text.index(END) + len(END):]
        return text.rstrip() + "\n\n" + new + "\n"
    return f"# AGENTS.md\n\n{new}\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--cwd", default=".")
    ap.add_argument("--direction", default="")
    ap.add_argument("--out", default=None)
    ap.add_argument("--agents", default=None)
    ap.add_argument("--quiet", action="store_true")
    args = ap.parse_args()

    root = Path(args.cwd).resolve()
    project = root.name
    disciplines = detect_disciplines(root)
    gaps = detect_gaps(root)

    team_yaml = build_team_yaml(project, args.direction or "(no PROJECT-DIRECTION provided)", disciplines, gaps)
    if not args.quiet:
        (Path(args.out) if args.out else root / "team.yaml").write_text(team_yaml)
        agents_path = Path(args.agents) if args.agents else root / "AGENTS.md"
        agents_path.write_text(merge_agents(agents_path, agents_block(project, disciplines, gaps)))

    disc_str = ", ".join(f"{d}→{s}" for d, s, _ in disciplines) or "none"
    print(f"[gen-team] {project}: disciplines [{disc_str}] · {len(T.ROLES)} roles · {len(gaps)} gap(s)")
    for g in gaps:
        print(f"  GAP: {g['marker']} (likely {g['likely_discipline']}) — resolve by judgment, then add to team_table.py")
    return 0


if __name__ == "__main__":
    sys.exit(main())
